sonar.projectKey=activity-manager
sonar.projectName=Activity Manager
sonar.projectVersion=1.0

sonar.sources=app,routes
sonar.exclusions=vendor/**,storage/**,tests/**

sonar.host.url=http://localhost:9000